version: '3.5'

services:

  mssql_server:
    container_name: mssql_server
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1402:1433"
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    restart: unless-stopped

  flyway:
    image: flyway/flyway
    command: -mixed=true -url="jdbc:sqlserver://mssql_server;databaseName=master;encrypt=false;trustServerCertificate=true;user=sa;Password=P@ssw0rd" migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - mssql_server
  checkout-service:
    build: .
    ports:
      - "7071:80"
      
    
volumes:
    mssql_server:
