USE [checkout-service];
Go

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' 
AND TABLE_NAME='Basket' AND COLUMN_NAME='Close' )
   ALTER TABLE dbo.[Basket] ADD [Close] bit NOT NULL DEFAULT 0

GO

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dbo' 
AND TABLE_NAME='Basket' AND COLUMN_NAME='Payed' )
   ALTER TABLE dbo.[Basket] ADD Payed bit NOT NULL DEFAULT 0
GO
